
import javax.swing.JSlider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author romai
 */
public class Accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Accueil.class.getName());

    /**
     * Creates new form Accueil
     */
    public Accueil() {
         initComponents();
    
       
        
    }

    public JSlider getSlider_Niveau() {
        return slider_Niveau;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Titre_jeu = new javax.swing.JLabel();
        Bouton_Start = new javax.swing.JButton();
        slider_Niveau = new javax.swing.JSlider();
        lbl_choix_niveau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Titre_jeu.setFont(new java.awt.Font("Avenir Next Cyr", 0, 36)); // NOI18N
        lbl_Titre_jeu.setText("Cadenas");
        getContentPane().add(lbl_Titre_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        Bouton_Start.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
        Bouton_Start.setText("Start");
        Bouton_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_StartActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        slider_Niveau.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
        slider_Niveau.setMajorTickSpacing(5);
        slider_Niveau.setMaximum(25);
        slider_Niveau.setMinimum(5);
        slider_Niveau.setPaintLabels(true);
        getContentPane().add(slider_Niveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, 40));

        lbl_choix_niveau.setText("Veuillez choisir votre niveau");
        getContentPane().add(lbl_choix_niveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_StartActionPerformed
         int niveau = slider_Niveau.getValue();

        FenetreCadenas jeu = new FenetreCadenas(niveau);
        jeu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_Bouton_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_Start;
    private javax.swing.JLabel lbl_Titre_jeu;
    private javax.swing.JLabel lbl_choix_niveau;
    private javax.swing.JSlider slider_Niveau;
    // End of variables declaration//GEN-END:variables
}
