/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author romai
 */
public class FenetreCadenas extends javax.swing.JFrame {
    
    
    
    public FenetreCadenas(int niveau) {
    
        
    combi = new Combinaison();   
    combi.genererCombinaison();
    initComponents();
    this.maxTentatives = niveau;
    
}

    private Combinaison combi;
    private int tentative = 0;
    private int maxTentatives;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreCadenas.class.getName());

    /**
     * Creates new form FenetreCadenas
     */
    public FenetreCadenas() {

        initComponents();
        combi.genererCombinaison();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_hauts = new javax.swing.JLabel();
        texte_nb_chiffres_hauts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        teste_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        Bouton_Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
        texte_intro.setText("Trouver le bon code en moins de 5 tentatives");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        up_chiffre_1.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

            up_chiffre_2.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

                up_chiffre_3.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

                    up_chiffre_4.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

                        texte_chiffre_1.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_chiffre_1.setText("0");
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

                        texte_chiffre_2.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_chiffre_2.setText("0");
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_chiffre_3.setText("0");
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

                        texte_chiffre_4.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_chiffre_4.setText("0");
                        getContentPane().add(texte_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

                        down_chiffre_1.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

                        down_chiffre_2.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

                        down_chiffre_3.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

                        down_chiffre_4.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

                        bouton_tester.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

                        texte_nb_chiffres_exacts.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_nb_chiffres_exacts.setText("Exacts : 0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

                        texte_lbl_nb_chiffres_hauts.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_lbl_nb_chiffres_hauts.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(texte_lbl_nb_chiffres_hauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

                        texte_nb_chiffres_hauts.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_nb_chiffres_hauts.setText("Trop bas : 0");
                        getContentPane().add(texte_nb_chiffres_hauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

                        texte_lbl_nb_chiffres_bas.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

                        texte_nb_chiffres_bas.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_nb_chiffres_bas.setText("Trop bas : 0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

                        texte_score.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        texte_score.setText("Tentatives");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

                        teste_tentatives.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        teste_tentatives.setText("Tentatives : 0");
                        getContentPane().add(teste_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

                        bouton_recommencer.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

                        Bouton_Menu.setFont(new java.awt.Font("Avenir Next Cyr", 0, 12)); // NOI18N
                        Bouton_Menu.setText("Menu");
                        Bouton_Menu.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Bouton_MenuActionPerformed(evt);
                            }
                        });
                        getContentPane().add(Bouton_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        int value = Integer.parseInt(texte_chiffre_3.getText());
        if (value < 9) {
            texte_chiffre_3.setText(String.valueOf(value + 1));
        }// TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        int value = Integer.parseInt(texte_chiffre_1.getText());
        if (value > 0) {
            texte_chiffre_1.setText(String.valueOf(value - 1));
        }// TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        int value = Integer.parseInt(texte_chiffre_1.getText());
        if (value < 9) {
            texte_chiffre_1.setText(String.valueOf(value + 1));
        }
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        if (tentative >= maxTentatives) {
        texte_intro.setText("Vous avez perdu !");
            return;
            
        }

        tentative++;

        int[] prop = new int[4];
        prop[0] = Integer.parseInt(texte_chiffre_1.getText());
        prop[1] = Integer.parseInt(texte_chiffre_2.getText());
        prop[2] = Integer.parseInt(texte_chiffre_3.getText());
        prop[3] = Integer.parseInt(texte_chiffre_4.getText());

        
        teste_tentatives.setText("Tentatvies : "+tentative + "/" + maxTentatives);
        

        int exacts = combi.compterChiffresExacts(prop);
        texte_nb_chiffres_exacts.setText("Exacts : " + exacts);

        int hauts = combi.compterChiffresTropHauts(prop);
        int bas = combi.compterChiffresTropBas(prop);

        texte_nb_chiffres_hauts.setText("Trop hauts : " + hauts);
        texte_nb_chiffres_bas.setText("Trop bas : " + bas);


    }//GEN-LAST:event_bouton_testerActionPerformed


    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        int value = Integer.parseInt(texte_chiffre_2.getText());
        if (value < 9) {
            texte_chiffre_2.setText(String.valueOf(value + 1));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        int value = Integer.parseInt(texte_chiffre_4.getText());
        if (value < 9) {
            texte_chiffre_4.setText(String.valueOf(value + 1));
        }

    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        int value = Integer.parseInt(texte_chiffre_4.getText());
        if (value > 0) {
            texte_chiffre_4.setText(String.valueOf(value - 1));
        }// TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        int value = Integer.parseInt(texte_chiffre_3.getText());
        if (value > 0) {
            texte_chiffre_3.setText(String.valueOf(value - 1));
        }// TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        int value = Integer.parseInt(texte_chiffre_2.getText());
        if (value > 0) {
            texte_chiffre_2.setText(String.valueOf(value - 1));
        }
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        texte_chiffre_1.setText("0");
        texte_chiffre_2.setText("0");
        texte_chiffre_3.setText("0");
        texte_chiffre_4.setText("0");

        texte_nb_chiffres_exacts.setText("Exacts : 0");
        texte_nb_chiffres_hauts.setText("Trop hauts : 0");
        texte_nb_chiffres_bas.setText("Trop bas : 0");

        combi.genererNouvelleCombinaison();
        
        tentative=0;
        teste_tentatives.setText("Tentatvies : "+tentative + "/" + maxTentatives);
        texte_intro.setText("Trouver le bon code en moins de 5 tentatives");
        

    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void Bouton_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_MenuActionPerformed
        this.dispose();
        Accueil accueil = new Accueil();
        accueil.setVisible(true);
        
    }//GEN-LAST:event_Bouton_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreCadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_Menu;
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel teste_tentatives;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_hauts;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_hauts;
    private javax.swing.JLabel texte_score;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
