/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author romai
 */
public class Accueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Accueil.class.getName());

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        
   
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Slog = new javax.swing.JLabel();
        lbl_Titre = new javax.swing.JLabel();
        lbl_Consignes = new javax.swing.JLabel();
        Button_Start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Slog.setFont(new java.awt.Font("BuloRounded-Black", 0, 12)); // NOI18N
        lbl_Slog.setForeground(new java.awt.Color(119, 126, 140));
        lbl_Slog.setText("A tiny puzzle that grows on you.");
        getContentPane().add(lbl_Slog, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 170, 50));

        lbl_Titre.setFont(new java.awt.Font("BuloRounded-Black", 0, 36)); // NOI18N
        lbl_Titre.setText("<html><span style='color:rgb(107, 205, 253);'>T</span><span style='color:rgb(253, 105, 131);'>H</span><span style='color:rgb(119, 126, 140)';>REES</span></html>");
        getContentPane().add(lbl_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 60));

        lbl_Consignes.setFont(new java.awt.Font("BuloRounded-Black", 0, 10)); // NOI18N
        lbl_Consignes.setText("<html>Threes est un jeu de puzzle assez proche du jeu 2048, dans lequel vous disposez d’une grille de 4 par 4 contenant des nombres.  <br><br> A chaque tour de jeu, un nombre, 1, ou 2, apparait sur un des bords disponibles de la grille. <br> <br> A chaque tour de jeu également, le joueur choisit une direction parmi les 4 points cardinaux :  <br> <br> -     Les éléments sont tous décalés d’une case vers la direction correspondante si la case est libre. <br> -     Si un élément entre en collision avec un élément de même valeur, ils fusionnent et la valeur résultante double   <br> -     Si un 1 rentre en collision avec un 2, ils s’additionnent. <br><br> La partie s’arrête quand la grille est remplie et qu’il n’est plus possible d’ajouter un élément. <br><br> L’objectif est de maximiser le nombre de coups joués.  <html>");
        lbl_Consignes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_Consignes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 490, 220));

        Button_Start.setFont(new java.awt.Font("BuloRounded-Black", 0, 12)); // NOI18N
        Button_Start.setText("Start");
        Button_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_StartActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_StartActionPerformed
        FenetrePrincipale jeu = new FenetrePrincipale(); 
        jeu.setVisible(true);

    
    this.dispose();
    }//GEN-LAST:event_Button_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Accueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Start;
    private javax.swing.JLabel lbl_Consignes;
    private javax.swing.JLabel lbl_Slog;
    private javax.swing.JLabel lbl_Titre;
    // End of variables declaration//GEN-END:variables
}
