/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author romai
 */
public class FenetrePrincipale extends javax.swing.JFrame {
    private Jeu jeu;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName());

    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        
        initComponents();
        
        jeu = new Jeu();

    int nbLignes = 4;
    int nbColonnes = 4;


    PanneauGrille.setLayout(new java.awt.GridLayout(nbLignes, nbColonnes));


    for (int i = 0; i < nbLignes; i++) {
        for (int j = 0; j < nbColonnes; j++) {
            CelluleGraphique bouton = new CelluleGraphique(jeu, i, j);
            PanneauGrille.add(bouton);
        }
    }
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        Boutton_Haut = new javax.swing.JButton();
        Boutton_Bas = new javax.swing.JButton();
        Boutton_Gauche = new javax.swing.JButton();
        Boutton_Droite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(31, 50, 90));
        PanneauGrille.setPreferredSize(new java.awt.Dimension(200, 200));
        PanneauGrille.setLayout(new java.awt.GridLayout());
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 200, 200));

        Boutton_Haut.setText("/\\");
            Boutton_Haut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Boutton_HautActionPerformed(evt);
                }
            });
            getContentPane().add(Boutton_Haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

            Boutton_Bas.setText("\\/");
            Boutton_Bas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Boutton_BasActionPerformed(evt);
                }
            });
            getContentPane().add(Boutton_Bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

            Boutton_Gauche.setText("<");
            Boutton_Gauche.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Boutton_GaucheActionPerformed(evt);
                }
            });
            getContentPane().add(Boutton_Gauche, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

            Boutton_Droite.setText(">");
            Boutton_Droite.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Boutton_DroiteActionPerformed(evt);
                }
            });
            getContentPane().add(Boutton_Droite, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void Boutton_DroiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boutton_DroiteActionPerformed
        jeu.jouer("droite");
        PanneauGrille.repaint();
    }//GEN-LAST:event_Boutton_DroiteActionPerformed

    private void Boutton_HautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boutton_HautActionPerformed
        jeu.jouer("haut");
        PanneauGrille.repaint();
    }//GEN-LAST:event_Boutton_HautActionPerformed

    private void Boutton_BasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boutton_BasActionPerformed
        jeu.jouer("bas");
        PanneauGrille.repaint();
    }//GEN-LAST:event_Boutton_BasActionPerformed

    private void Boutton_GaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boutton_GaucheActionPerformed
        jeu.jouer("gauche");
        PanneauGrille.repaint();
    }//GEN-LAST:event_Boutton_GaucheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetrePrincipale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boutton_Bas;
    private javax.swing.JButton Boutton_Droite;
    private javax.swing.JButton Boutton_Gauche;
    private javax.swing.JButton Boutton_Haut;
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
