
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author romai
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form Interface
     */
    
    int compteur=0;
    int indexQuestionCourante = 0;
 
    public void afficherQuestionCourante(){
         Question q = questions.get(indexQuestionCourante);
           lblQuestion.setText(q.getIntitule());
           
          btnRep1.setText(q.getProposition1());
          btnRep2.setText(q.getProposition2());
          btnRep3.setText(q.getProposition3());
          btnRep4.setText(q.getProposition4());
          
          btnRep1.setEnabled(true);
          btnRep2.setEnabled(true);
          btnRep3.setEnabled(true); 
          btnRep4.setEnabled(true);
         

         
    }
    ArrayList<Question> questions = new ArrayList<>(); 

    public FenetreQuiz() {
        
questions.add(new Question("Capitale de la France ?", "Rome", "Berlin", "Paris", "Madrid", 3));
questions.add(new Question("Capitale de l’Espagne ?", "Barcelone", "Madrid", "Séville", "Valence", 2));
questions.add(new Question("Capitale de l’Allemagne ?", "Berlin", "Munich", "Hambourg", "Francfort", 1));
questions.add(new Question("Capitale de l’Italie ?", "Rome", "Milan", "Venise", "Turin", 1));
questions.add(new Question("Capitale du Portugal ?", "Lisbonne", "Porto", "Braga", "Faro", 1));

questions.add(new Question("Capitale du Royaume-Uni ?", "Manchester", "Liverpool", "Édimbourg", "Londres", 4));
questions.add(new Question("Capitale de la Suisse ?", "Zurich", "Genève", "Berne", "Bâle", 3));
questions.add(new Question("Capitale de la Belgique ?", "Bruges", "Bruxelles", "Liège", "Anvers", 2));
questions.add(new Question("Capitale des Pays-Bas ?", "Rotterdam", "Amsterdam", "La Haye", "Utrecht", 2));
questions.add(new Question("Capitale du Danemark ?", "Oslo", "Stockholm", "Copenhague", "Helsinki", 3));
questions.add(new Question("Capitale du Vietnam ?", "Hô-Chi-Minh-Ville", "Hanoi", "Hue", "Da Nang", 2));
    

        initComponents();
        lblQuestion.setVisible(true);
        
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep2 = new javax.swing.JButton();
        btnRep1 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        btnSuivant = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setFont(new java.awt.Font("Avenir Next Cyr", 0, 24)); // NOI18N
        lblQuestion.setText("BONJOUR");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        btnRep2.setFont(new java.awt.Font("Avenir Next Cyr", 0, 14)); // NOI18N
        btnRep2.setText("Ok");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 30));

        btnRep1.setFont(new java.awt.Font("Avenir Next Cyr", 0, 14)); // NOI18N
        btnRep1.setText("Ok");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 40));

        btnRep3.setFont(new java.awt.Font("Avenir Next Cyr", 0, 14)); // NOI18N
        btnRep3.setText("Ok");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, -1));

        btnRep4.setFont(new java.awt.Font("Avenir Next Cyr", 0, 14)); // NOI18N
        btnRep4.setText("Ok");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, -1));

        lblFeedback.setFont(new java.awt.Font("Avenir Next Cyr", 0, 14)); // NOI18N
        lblFeedback.setText("jLabel1");
        getContentPane().add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        btnSuivant.setFont(new java.awt.Font("Avenir Next Cyr", 0, 14)); // NOI18N
        btnSuivant.setText("jButton1");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Avenir Next Cyr", 0, 14)); // NOI18N
        jLabel1.setText("lblScore");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        lblQuestion.setVisible(true);
        
       
           int numeroChoisi = 2;
    Question q = questions.get(indexQuestionCourante);

    if (numeroChoisi == q.getIndexBonneReponse()) {
        lblFeedback.setText("Bonne réponse");
        
    } else {
        lblFeedback.setText("Mauvaise réponse");
    }
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
        
       
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
    int numeroChoisi = 1;          
    Question q = questions.get(indexQuestionCourante);   

    if (numeroChoisi == q.getIndexBonneReponse()) {
        lblFeedback.setText("Bonne réponse");                          
    } else {
        lblFeedback.setText("Mauvaise réponse");
    }

 
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
    
    int numeroChoisi = 3;
    Question q = questions.get(indexQuestionCourante);

    if (numeroChoisi == q.getIndexBonneReponse()) {
        lblFeedback.setText("Bonne réponse");
        
    } else {
        lblFeedback.setText("Mauvaise réponse");
    }
    
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
    
     int numeroChoisi = 4;
    Question q = questions.get(indexQuestionCourante);

    if (numeroChoisi == q.getIndexBonneReponse()) {
        lblFeedback.setText("Bonne réponse");
        
    } else {
        lblFeedback.setText("Mauvaise réponse");
    }   
        
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        indexQuestionCourante++; // passer à la question suivante

    if (indexQuestionCourante < questions.size()) {
        afficherQuestionCourante(); // afficher la question suivante
        lblFeedback.setText("");     // effacer le feedback précédent
    } else {
        lblFeedback.setText("Quiz terminé. Score : ");
        btnSuivant.setEnabled(false); // désactiver le bouton suivant
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
    }
    }//GEN-LAST:event_btnSuivantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}

